baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
[deployment]
  order = [".jpg", ".gif$"]

[[deployment.targets]]

name = "mydeployment"
URL = "s3://no-datadog-challenge?region=USEast"
